/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class utils_bot_DanielBotClasses_TEST */

#ifndef _Included_utils_bot_DanielBotClasses_TEST
#define _Included_utils_bot_DanielBotClasses_TEST
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     utils_bot_DanielBotClasses_TEST
 * Method:    nnueEvaluate
 * Signature: (I[J[J)I
 */
JNIEXPORT jint JNICALL Java_utils_bot_DanielBotClasses_TEST_nnueEvaluate
  (JNIEnv *, jobject, jint, jlongArray, jlongArray);

/*
 * Class:     utils_bot_DanielBotClasses_TEST
 * Method:    nnueInit
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_utils_bot_DanielBotClasses_TEST_nnueInit
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
